FROM php:8.1.0-fpm-alpine

ADD ./docker/config/php/fpm/www.conf /usr/local/etc/php-fpm.d/

RUN mkdir -p /var/www/html

WORKDIR /var/www/html

RUN apk update && apk add curl

RUN apk add --no-cache $PHPIZE_DEPS \
   freetype \
   libpng \
   libjpeg-turbo \
   freetype-dev \
   libwebp-dev \
   libpng-dev \
   libjpeg-turbo-dev \
   libxml2-dev \
   zlib-dev \
   libzip-dev \
   tidyhtml-dev \
   libxpm-dev

# composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

COPY ./docker/config/php/conf.d/opcache.ini /usr/local/etc/php/conf.d/opcache.ini

RUN docker-php-ext-install mysqli pdo pdo_mysql fileinfo && docker-php-ext-enable pdo_mysql

RUN docker-php-ext-configure gd --with-freetype --with-webp --with-jpeg && docker-php-ext-install -j$(nproc) gd


